### ISSUE TITLE
Preloaded images not hidden on Firefox

### ISSUE THREAD

**Issue by PVince81** [owncloud/files_mediaviewer#68] opened 2019-04-15 15:51 UTC
### Steps

1. Install owncloud-enterprise-complete bundle (for 10.2.0 RC1)
1. Install files_mediaviewer-1.0.0RC1
1. Upload many pictures
1. Open a picture in the middle of the list in Firefox

### Expected result
Only selected picture appears.

### Actual result
Three pictures appear, previous one on the left and next one on the right.

### Version
Broken with Firefox 66 on openSUSE Tumbleweed
On the same OS and server version but with Chromium 73 it works fine.

### Enabled apps
```
Enabled:
  - activity: 2.4.2
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.4.0
  - enterprise_key: 0.2.0
  - federatedfilesharing: 0.4.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.0
  - files_pdfviewer: 0.10.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - guests: 0.8.1
  - market: 0.4.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1
```

I didn't see this issue on my own server which has the same mediaviewer app, so it could be a CSS side effect from one of the installed apps.

This is the app list on the server where it works fine in Firefox:
```
Enabled:
  - activity: 2.4.2
  - calendar: 1.6.1
  - configreport: 0.1.2
  - contacts: 1.5.5
  - dav: 0.4.0
  - encryption: 1.3.1
  - federatedfilesharing: 0.3.1
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.0
  - files_pdfviewer: 0.10.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.1.1
  - market: 0.3.0
```

Note that my personal server (the latter one) is much slower than my local env where the issue happens. Not sure if the loading delay is "fixing" the issue.

@felixheidecke

**Comment by PVince81** [comment] 2019-04-15 16:16
no browser console error.

however by comparing with Chromium, I noticed that it's not using the correct CSS classes:
![image](https://user-images.githubusercontent.com/277525/56148429-8dd2eb00-5faa-11e9-99be-955773d7c66b.png)

it should set "swiper-slide-next" and "swiper-slide-active" but didn't here.
maybe the swiper component failed to boot up ?

**Comment by PVince81** [comment] 2019-04-15 16:18
I'm able to swipe though, but it's not aligned and rather chaotic.

it seems to put the pictures directly side by side instead of leaving a big space that puts the previous and next picture/video off screen

**Comment by PVince81** [comment] 2019-04-15 16:19
I tried setting the missing CSS classes by hand with the DOM inspector but it doesn't seem to affect anything.

Next up: disabling apps

**Comment by PVince81** [comment] 2019-04-15 16:27
I double checked by personal server where it all worked. It seems I still had the 1.0.0beta or some other test version where it worked.

I've installed 1.0.0RC1 there and now the bug also happens there with Firefox. Also I noticed that the pictures are appearing faster, maybe because they are read from cache.

So it's a regression from 1.0.0beta at least.

**Comment by PVince81** [comment] 2019-04-15 16:31
hmmm, I cleared cache and when pictures are loading extremely slow (spinners), the rendering looks fine.

I wonder if there's some kind of race condition that only causes trouble when the pictures are loaded from cache

**Comment by PVince81** [comment] 2019-04-15 16:36
easy to reproduce on local server, but more difficult on my remote slow server as it seems to be slow despite the fact that previews already exist on the server. Due to heavy preloading, the server-side cached preview is often still slow enough to not trigger the above issue

**Comment by felixheidecke** [comment] 2019-04-21 12:09
I re-tested as well and it works fine "unless" you activate the developer console which seems to interfere with the gallery for some reason. Close and open the dev tab while the gallery is active and it works fine. I am using the current master for testing and did not encounter any problems (despite the ones mentioned with the dev-console)

1. Opened the console
2. Scrolled down in the huge image list
3. waited for all thumbs to be loaded
4. emptied out the network tab
5. clicked an image

Result: three images were loaded. Preseeding, current and next.

**Comment by felixheidecke** [comment] 2019-04-21 12:10
Is there any other way to monitor network traffic without using the browser console?

**Comment by PVince81** [comment] 2019-04-22 16:00
why would the console cause trouble ? is it a CSS or vertical height thing ?

is there a way to analyze what's happening and why the CSS classes on the elements of the swiper are missing ? depending what it is there is a risk that it could also happen with other scenarios that do not involve the browser console.

**Comment by felixheidecke** [comment] 2019-04-23 07:16
The width and height of the container are being calculated by JS which ceases to work properly once the console is open. It also always jumps back to image 1 when navigating back no matter how far in the image list you are.

### Closing the console (no reloading after) miraculously fixes the problem.

![2019-04-23 08-51-08 2019-04-23 09_02_27](https://user-images.githubusercontent.com/12717530/56561111-87de9a80-65a6-11e9-9b5f-417e74570ca1.gif)

I have nooooo Idea what's going on there.

**Comment by felixheidecke** [comment] 2019-04-23 07:16
@PVince81 do you mind if we have a look @ it together via jitsi? I can schedule a short 1:1.

**Comment by felixheidecke** [comment] 2019-04-29 08:50
This is "resolved" (in quotes) … right?

**Comment by PVince81** [comment] 2019-04-29 08:54
if this is only a console thing then let's close it for now... if people report this in other contexts we can reopen

**Comment by PVince81** [comment] 2019-05-03 07:34
@skshetry you reported seeing this, can you clarify whether you had the browser console open ?

**Comment by skshetry** [comment] 2019-05-03 08:09
@PVince81, I tried on `safe mode` and it didn't happen. No, the console was not opened. Maybe, the addons are to blame.

**Comment by felixheidecke** [comment] 2019-06-11 10:59
I can't reproduce the bug anymore. Close @skshetry ?

**Comment by skshetry** [comment] 2019-06-11 11:06
Yeah, let's close this for now.  Anyone that encounters this again, feel free to open if it happens. For me, it looked like some addons were interfering with this app (or, opened devtools). So, please file a bug with extensions enabled (only happened in firefox).

**Closed by skshetry** 2019-06-11 11:06 UTC
Labels: bug, p2-high
