### ISSUE TITLE
[QA] mediaviewer does not show *.heic images

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_mediaviewer#914] opened 2023-08-22 13:17 UTC
Seen with 10.13.0-rc.2 and files_mediaviewer 1.0.5

* docker run --rm -ti -p 6660:8080 -d owncloud/server:10.13.0-rc.2
* firefox localhost:6660
* Navigate to the photos folder. Upload a heic image. A thumbnail is generated. OK
* click on the uploaded image. It gets downloaded. BAD
* click on other image, mediaviewer opens. OK
* but mediaviewer shows all except for the heic images. BAD

**Comment by phil-davis** [comment] 2023-08-22 14:46
Is this a new problem?
It is a few years since the last release tag https://github.com/owncloud/files_mediaviewer/releases/tag/v1.0.5
There have been lots of dependabot dependency bump updates since then. The first thing to try would be to make a 1.0.6-rc from current master and see what works...

**Comment by jvillafanez** [comment] 2023-08-30 08:51
Confirmed. It still happen in the current master (post 10.13).

It seems the problem is the the interpretation of the mime type. In https://github.com/owncloud/core/blob/6bf7652851bea5735fc2b57d15251c9a8a231a28/lib/private/PreviewManager.php#L340 the target mimetype is "image/hei(f|c)". I guess the mediaviewer (or whatever needs to interpret this mimetype) uses the "image/hei(f|c)" instead of "image/heif or image/heic". Using just "image/heic" solves the problem, although it will break with "image/heif" files.

The problem is likely in core because the mediaviewer tries to register the "image/hei(f|c)" type, but core might nor be able to match it with actual "image/heic" types.
The alternative is to provide 2 different providers in https://github.com/owncloud/core/blob/6bf7652851bea5735fc2b57d15251c9a8a231a28/lib/private/PreviewManager.php#L340. This seems to be the best option.
```
'HEIC'	=> ['mimetype' => '/image\/heic/', 'class' => '\OC\Preview\Heic'],
'HEIF'	=> ['mimetype' => '/image\/heif/', 'class' => '\OC\Preview\Heic'],
```

**Comment by cdamken** [comment] 2023-09-15 06:17
I tested with @jvillafanez yesterday and we did this:

1.- Update the ImageMagick version:
https://doc.owncloud.com/server/10.13/admin_manual/installation/manual_installation/manual_imagick7.html

BTW, in my server did not work this documentation because I had 20.04 we downloaded it from GitHub but not the latest version:
https://github.com/SoftCreatR/imei

@mmattel We have to change the documentation because is not as described.

2.- We modified the code in ownCloud:

Line 340 from lib/private/PreviewManager.php
```
#'HEIC'	=> ['mimetype' => '/image\/hei(f|c)/', 'class' => '\OC\Preview\Heic'],
'HEIC'	=> ['mimetype' => '/image\/heic/', 'class' => '\OC\Preview\Heic'],
'HEIF'	=> ['mimetype' => '/image\/heif/', 'class' => '\OC\Preview\Heic'],
```
Now it works.

BTW, works with Files_Mediaviewer and Gallery App

**Comment by jnweiger** [comment] 2023-09-21 08:43
@cdamken The entry for SVG has another backslash. Does that wok with mediaviewer? '/image\/svg\+xml/'
What I understand here, is that mediaviewer does not fully support the regexp syntax that we had here. Right?

**Comment by pako81** [comment] 2023-09-25 13:54
https://github.com/owncloud/core/pull/40990 has just been merged, closing this.

**Closed by pako81** 2023-09-25 13:54 UTC
